'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ecacerest@finagil.com.mx")>  _
        Public Property MailError() As String
            Get
                Return CType(Me("MailError"),String)
            End Get
            Set
                Me("MailError") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\CFDIbackup\")>  _
        Public Property RutaBackup() As String
            Get
                Return CType(Me("RutaBackup"),String)
            End Get
            Set
                Me("RutaBackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\")>  _
        Public Property NoPasa() As String
            Get
                Return CType(Me("NoPasa"),String)
            End Get
            Set
                Me("NoPasa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\ORGtxt\")>  _
        Public Property RutaOrigen() As String
            Get
                Return CType(Me("RutaOrigen"),String)
            End Get
            Set
                Me("RutaOrigen") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=server-raid2;Initial Catalog=Production;Persist Security Info=True;Us"& _ 
            "er ID=User_PRO;Password=User_PRO2015")>  _
        Public ReadOnly Property ConnectionStringFACTURA() As String
            Get
                Return CType(Me("ConnectionStringFACTURA"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\")>  _
        Public Property Raiz() As String
            Get
                Return CType(Me("Raiz"),String)
            End Get
            Set
                Me("Raiz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\ORGtxt\Complementos\")>  _
        Public Property Complementos() As String
            Get
                Return CType(Me("Complementos"),String)
            End Get
            Set
                Me("Complementos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\FTPEkomercio\Backup\")>  _
        Public Property BackupEKO() As String
            Get
                Return CType(Me("BackupEKO"),String)
            End Get
            Set
                Me("BackupEKO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\FTPEkomercio\")>  _
        Public Property FtpDatos() As String
            Get
                Return CType(Me("FtpDatos"),String)
            End Get
            Set
                Me("FtpDatos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\FoliosEkomercio\")>  _
        Public Property RutaFolios() As String
            Get
                Return CType(Me("RutaFolios"),String)
            End Get
            Set
                Me("RutaFolios") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\FTPEkomercio\")>  _
        Public Property RutaFTP() As String
            Get
                Return CType(Me("RutaFTP"),String)
            End Get
            Set
                Me("RutaFTP") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wslamoderna.ekomercio.com/WSCFDIBuilderPlus/WSCFDBuilderPlus.asmx")>  _
        Public ReadOnly Property GeneraFactura33_WebReference_Ek_WSCFDBuilderPlus() As String
            Get
                Return CType(Me("GeneraFactura33_WebReference_Ek_WSCFDBuilderPlus"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=server-raid2;Initial Catalog=Production;User ID=finagil;Password=fina"& _ 
            "gil")>  _
        Public ReadOnly Property ProductionConnectionString() As String
            Get
                Return CType(Me("ProductionConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\Contabilidad CFDI\ARCHIVOS ADD CONTPAQi\CFDI_CLI\")>  _
        Public Property RutaXML() As String
            Get
                Return CType(Me("RutaXML"),String)
            End Get
            Set
                Me("RutaXML") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\RecibosPago\")>  _
        Public Property RutaRecPago() As String
            Get
                Return CType(Me("RutaRecPago"),String)
            End Get
            Set
                Me("RutaRecPago") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-nas\FacturasCFDI\FTPEkomercioNomina\")>  _
        Public Property RutaNomina() As String
            Get
                Return CType(Me("RutaNomina"),String)
            End Get
            Set
                Me("RutaNomina") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://148.244.217.118/WSCFDIBuilderPlus/WSCFDBuilderPlus.asmx")>  _
        Public ReadOnly Property GeneraFactura33_WebReferenceNomina_Ek_WSCFDBuilderPlus() As String
            Get
                Return CType(Me("GeneraFactura33_WebReferenceNomina_Ek_WSCFDBuilderPlus"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=server-raid2;Initial Catalog=ComunInfo100;Persist Security Info=True;"& _ 
            "User ID=sa;Password=c3r0&v4n")>  _
        Public ReadOnly Property ComunInfo100cs() As String
            Get
                Return CType(Me("ComunInfo100cs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server-raid2\TmpFinagil\")>  _
        Public Property RutaTmp() As String
            Get
                Return CType(Me("RutaTmp"),String)
            End Get
            Set
                Me("RutaTmp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp85.cmoderna.com")>  _
        Public Property SMTP() As String
            Get
                Return CType(Me("SMTP"),String)
            End Get
            Set
                Me("SMTP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("26")>  _
        Public Property SMTP_port() As String
            Get
                Return CType(Me("SMTP_port"),String)
            End Get
            Set
                Me("SMTP_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ecacerest,c4c3r1t0s,cmoderna")>  _
        Public Property SMTP_creden() As String
            Get
                Return CType(Me("SMTP_creden"),String)
            End Get
            Set
                Me("SMTP_creden") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GeneraFactura.My.MySettings
            Get
                Return Global.GeneraFactura.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
